/* ContentPad Arcade — the game catalog (build 2026100604-hf).
   House games live in this repo as <slug>.html at the top level and are listed here.
   Only status:'live' entries are shown. rating marks adult games (the game itself runs its own age gate). */
window.ARCADE_GAMES = [
  {
    slug: 'high-flying',
    file: 'high-flying.html',
    title: 'Slappy Tha Bear: High Flying',
    badge: 'New · Slapwoods × ContentPad · twin-stick aim',
    tagline: 'Slappy Tha Bear vs. the Buzzkill Armada. Pew pew pew. Blast your way to the top of the sky.',
    about: "Slappy the Bear, the Slapwoods mascot, straps into his orange starfighter to take the sky back from Baron Buzzkill and the Buzzkill Armada. A 3D rail shooter in the old-school space-fighter style: three stages, from a golden-hour sunset over H-Town, through the lightning of Thunder Canyon, up to the Stratosphere, with a boss gunship at the end of each and the Killjoy Dreadnought waiting at the top. Twin lasers, hold-to-charge lock-on shots, barrel rolls that knock enemy fire away, Slap Bombs, boost and brake. Upgrade from Natural lasers to Russian Cream twins to Bloodshot hyper lasers, grab honey pots and gold rings to fix your shield, wipe out whole formations for bonuses and earn a medal on every stage. Presented by Slapwoods. 21+ only.",
    genre: 'Shooter',
    tags: ['21+', 'Shooter', '3D', '3 stages', 'Bosses', 'Slapwoods', 'Controller'],
    controls: [['WASD / arrows / left stick', 'Fly'], ['Right stick / arrows / mouse', 'Aim — twin-stick, mouse or classic, in Controls & flight'], ['Space / J / RT / click', 'Fire · hold and let go for a lock-on shot'], ['Q / E / LB / RB', 'Barrel roll · or double-tap a direction'], ['B / K / (B)', 'Slap Bomb'], ['Shift / hold (A)', 'Boost — faster while held'], ['C / (Y) / LT', 'Brake'], ['P / Esc / Start', 'Pause'], ['M', 'Mute']],
    by: 'ContentPad Studios × Slapwoods',
    made: 'Art made in ContentPad Studio · Slappy and the Slapwoods logo courtesy of Slapwoods · music, sound and code by Claude',
    scoreLabel: 'Best score',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/c76accf6-c3bb-4794-8f57-6d9f0879f7c5.png',
    accent: '#ff8a1c',
    released: '2026-10-06',
    rating: '21+',
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'dad-casino',
    file: 'dad-casino.html',
    title: "Dex Ain't Dead Casino",
    badge: 'New · Dex is dealing',
    tagline: 'Blackjack, baccarat, roulette, craps and the slots. Dex deals. Play money only.',
    about: "Pull up a seat at Dex Ain't Dead's own casino. Dex deals every table himself, in his own voice: blackjack that pays 3 to 2, baccarat, single-zero roulette, craps with odds, and Dead Man's Jackpot, a five-reel slot with free spins and a 1,000× skull jackpot. DAD Radio plays Dex's records the whole time. Everything is in US dollars to the cent. You start with $10,000 in play money, the house spots you $2,500 when you go broke, and there's a free $2,500 stack every four hours. The lobby tracks your peak bankroll and your lifetime net win or loss. Sign in to the Arcade and your bankroll follows you to any device. Play money only: nothing to buy, nothing to cash out. 18+.",
    genre: 'Casino',
    tags: ['Casino', 'Blackjack', 'Roulette', 'Craps', 'Baccarat', 'Slots', 'Play money', 'Controller'],
    controls: [['Tap a spot', 'Place the selected chip'], ['1 – 6', 'Pick a chip'], ['Space / Enter / Start', 'Deal · spin · roll'], ['H S D P', 'Blackjack: hit, stand, double, split'], ['D-pad + A', 'Move between buttons and press'], ['Esc / B', 'Back to the lobby'], ['M', 'Mute']],
    by: "ContentPad Studios × Dex Ain't Dead",
    made: "Art and Dex's dealer voice made in ContentPad Studio · music by Dex Ain't Dead · code by Claude",
    scoreLabel: 'Peak bankroll',
    scorePrefix: '$',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/227b6d27-8cf7-4ad2-b411-6cf6e9b7e5ee.png',
    accent: '#C9A84C',
    released: '2026-10-04',
    rating: '18+',
    quietSync: true,
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'nightmare-on-46th',
    file: 'nightmare-on-46th.html',
    title: 'Nightmare on 46th Street',
    badge: 'v4 · faster fights, harder hits, run and backdash',
    tagline: 'Six legends. One cursed DJ. Survive till 3 AM.',
    about: 'Halloween at Harbor, 621 West 46th Street. At midnight a DJ nobody booked drops a cursed record, the dance floor splits open and New York\'s legends crawl out of the speakers. Pick Vexa the Bottle Queen, Stitch the Doorman, the Rat King, Jack Spokes, Madame 46 or Glow, and fight across the Harbor dance floor, 46th Street, the subway and the rooftop to take down The Headliner. Specials, blocking, crouching sweeps and a Midnight Meter super for every fighter. Every fighter is fully voiced, with their own grunts, move calls, trash talk and signature sounds. Beat the arcade to unlock two secret fighters, or fight a friend in 2-player Versus. Plays with any controller, including 8BitDo.',
    genre: 'Fighting',
    tags: ['Fighting', 'Halloween', 'New York', '8 fighters', 'Voiced', '2 players', 'Controller'],
    controls: [['← → / A D', 'Walk · hold away to block · double-tap forward to run, back to backdash'], ['↑ / W', 'Jump'], ['↓ / S', 'Crouch · crouch + kick sweeps'], ['J / Z', 'Punch'], ['K / X', 'Kick'], ['L / C or ↓↘→ + punch', 'Special'], ['I / V', 'Super, when the Midnight Meter is full'], ['P / Esc / Start', 'Pause'], ['Versus', 'P1 WASD + F G H T · P2 arrows + , . / ;']],
    by: 'ContentPad Studios × Dream Hospitality',
    made: 'Art, music and announcer made in ContentPad Studio · written and coded by Claude',
    scoreLabel: 'Best score',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/ccc90bc0-3155-47c2-8c1a-a6a9596b4ce6.png',
    accent: '#ff7a1a',
    released: '2026-10-04',
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'skyline-dash',
    file: 'skyline-dash.html',
    title: 'Maverick: Skyline Dash',
    badge: 'v5 · Subway, Airport, Loop City · real kickflips',
    tagline: 'Skate the rooftops. Chain the tricks. Bank the combo.',
    about: 'Maverick took his board to the roofs, then underground, then to the airport. The kickflip is real now: the board leaves his feet and turns over. Heelflips, hardflips, varials, 360 flips, and doubles and triples if you have the air. Hold a grab — frontside, melon or method — and tweak it for more. Shove-it, 360 spin, even a 720 on vert. Grind and boardslide the rails, manual between tricks, launch off ramps and vert quarter-pipes, and roll all the way round loop-de-loops. Dodge rising security gates, ride moving walkways and sliding platforms while express trains blast through the station and planes take off behind you. Bank big combos, grab S-K-A-T-E and earn your crew. Eleven levels — the rooftops, SUBWAY RUSH, TERMINAL 4 and LOOP CITY — then see how far you get in Endless. Every trick works on a controller.',
    genre: 'Skate',
    tags: ['Skateboarding', '11 levels', 'Endless', 'Grabs', 'Loops', 'Crew', 'Controller'],
    controls: [['Space / tap / (A)', 'Ollie — hold for height'], ['Again in the air', 'Kickflip · hold ← heelflip · → hardflip · up to 3'], ['J / K / (Y) / RB / GRAB — hold', 'Grab · ← melon · → method · hold to tweak'], ['↓ / swipe down / TRICK / (X)', 'Shove-it in the air · again = 360 spin'], ['↓ on the ground', 'Manual — keeps your combo alive'], ['↓ on a rail', 'Boardslide'], ['Land on a rail', 'Grind it'], ['Land clean', 'Bank your combo'], ['P / Esc / Start', 'Pause menu'], ['M', 'Mute']],
    by: 'ContentPad Studios',
    made: 'Art and music made in ContentPad Studio · code by Claude',
    scoreLabel: 'Best total',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/6402676d-dc77-4014-9ccd-39cd14f81267.png',
    accent: '#ff4fb3',
    released: '2026-10-05',
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'tre-and-jada',
    file: 'tre-and-jada.html',
    title: 'Tre & Jada',
    badge: 'Episode 1 · Payday',
    rating: '18+',
    tagline: 'Keep the relationship alive. Keep your wallet alive. Pick one.',
    about: 'A fully voiced, choose-your-path relationship comedy for grown folks, set in Brooklyn. One week, payday to rent day: a brunch ambush and a "man pays for everything" table debate, a double shift on Flatbush, the group chat, a DUMBO photo shoot for the gram, the mall, a Williamsburg restaurant with no prices, and her mama\'s potato salad. Seven mini-games, animated cutscenes, nine endings. Most of them are your fault.',
    genre: 'Story comedy',
    tags: ['18+', 'Comedy', 'Brooklyn', '7 mini-games', '9 endings', 'Voiced'],
    controls: [['Click / tap / Space / (A)', 'Next line'], ['1 · 2 · 3 / ↑ ↓ / d-pad', 'Pick a choice'], ['Esc / Start', 'Pause and settings'], ['Y', 'Auto-play'], ['L / X', 'Dialogue log']],
    by: 'ContentPad Studios',
    made: 'Art, voices and music made in ContentPad Studio (ElevenLabs) · written and coded by Claude',
    scoreLabel: 'Endings found',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/f65c9ecd-ff8b-43cf-ab89-76f862120282.png',
    accent: '#ff4fd8',
    released: '2026-10-03',
    controller: true, mobile: true,
    status: 'live'
  }
];
