/* ContentPad Arcade — the game catalog (build 2026100408-casino).
   House games live in this repo as <slug>.html at the top level and are listed here.
   Only status:'live' entries are shown. rating marks adult games (the game itself runs its own age gate). */
window.ARCADE_GAMES = [
  {
    slug: 'dad-casino',
    file: 'dad-casino.html',
    title: "Dex Ain't Dead Casino",
    badge: 'New · Dex is dealing',
    tagline: 'Blackjack, baccarat, roulette, craps and the slots. Dex deals. Play money only.',
    about: "Pull up a seat at Dex Ain't Dead's own casino. Dex deals every table himself, in his own voice: blackjack that pays 3 to 2, baccarat, single-zero roulette, craps with odds, and Dead Man's Jackpot, a five-reel slot with free spins and a 1,000× skull jackpot. DAD Radio plays Dex's records the whole time. You start with 10,000 play-money chips, the house spots you when you go broke, and there's a free stack every four hours. Sign in to the Arcade and your bankroll follows you to any device. Play money only: nothing to buy, nothing to cash out. 18+.",
    genre: 'Casino',
    tags: ['Casino', 'Blackjack', 'Roulette', 'Craps', 'Baccarat', 'Slots', 'Play money', 'Controller'],
    controls: [['Tap a spot', 'Place the selected chip'], ['1 – 6', 'Pick a chip'], ['Space / Enter / Start', 'Deal · spin · roll'], ['H S D P', 'Blackjack: hit, stand, double, split'], ['D-pad + A', 'Move between buttons and press'], ['Esc / B', 'Back to the lobby'], ['M', 'Mute']],
    by: "ContentPad Studios × Dex Ain't Dead",
    made: "Art and Dex's dealer voice made in ContentPad Studio · music by Dex Ain't Dead · code by Claude",
    scoreLabel: 'Peak bankroll',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/227b6d27-8cf7-4ad2-b411-6cf6e9b7e5ee.png',
    accent: '#C9A84C',
    released: '2026-10-04',
    rating: '18+',
    quietSync: true,
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'nightmare-on-46th',
    file: 'nightmare-on-46th.html',
    title: 'Nightmare on 46th Street',
    badge: 'New · Halloween at Harbor NYC',
    tagline: 'Six legends. One cursed DJ. Survive till 3 AM.',
    about: 'Halloween at Harbor, 621 West 46th Street. At midnight a DJ nobody booked drops a cursed record, the dance floor splits open and New York\'s legends crawl out of the speakers. Pick Vexa the Bottle Queen, Stitch the Doorman, the Rat King, Jack Spokes, Madame 46 or Glow, and fight across the Harbor dance floor, 46th Street, the subway and the rooftop to take down The Headliner. Specials, blocking, crouching sweeps and a Midnight Meter super for every fighter. Every fighter is fully voiced, with their own grunts, move calls, trash talk and signature sounds. Beat the arcade to unlock two secret fighters, or fight a friend in 2-player Versus. Plays with any controller, including 8BitDo.',
    genre: 'Fighting',
    tags: ['Fighting', 'Halloween', 'New York', '8 fighters', 'Voiced', '2 players', 'Controller'],
    controls: [['← → / A D', 'Walk · hold away to block'], ['↑ / W', 'Jump'], ['↓ / S', 'Crouch · crouch + kick sweeps'], ['J / Z', 'Punch'], ['K / X', 'Kick'], ['L / C or ↓↘→ + punch', 'Special'], ['I / V', 'Super, when the Midnight Meter is full'], ['P / Esc / Start', 'Pause'], ['Versus', 'P1 WASD + F G H T · P2 arrows + , . / ;']],
    by: 'ContentPad Studios × Dream Hospitality',
    made: 'Art, music and announcer made in ContentPad Studio · written and coded by Claude',
    scoreLabel: 'Best score',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/ccc90bc0-3155-47c2-8c1a-a6a9596b4ce6.png',
    accent: '#ff7a1a',
    released: '2026-10-04',
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'skyline-dash',
    file: 'skyline-dash.html',
    title: 'Maverick: Skyline Dash',
    badge: 'v4 · the crew, the Locker, new tricks',
    tagline: 'Skate the rooftops. Chain the tricks. Bank the combo.',
    about: 'Maverick took his board to the roofs. Ollie the gaps, kickflip, shove-it and 360 spin in the air, manual between tricks to keep a combo alive, grind and boardslide the rails, launch off ramps and time the window-washer lifts. Bank big combos, grab S-K-A-T-E and earn your crew — Kiko and Dre drop in and skate with you, each with a perk. Level up your rider to unlock colorways, trails and a starting crew in the Locker. Eight levels from sunset to the top of the Spire, then see how far you get in Endless.',
    genre: 'Skate',
    tags: ['Skateboarding', '8 levels', 'Endless', 'Crew', 'Customize', 'Controller'],
    controls: [['Space / tap / (A)', 'Ollie — hold for height'], ['Again in the air', 'Kickflip'], ['↓ / swipe down / TRICK / (X)', 'Shove-it in the air · again = 360 spin'], ['↓ on the ground', 'Manual — keeps your combo alive'], ['↓ on a rail', 'Boardslide'], ['Land on a rail', 'Grind it'], ['Land clean', 'Bank your combo'], ['P / Esc / Start', 'Pause menu'], ['M', 'Mute']],
    by: 'ContentPad Studios',
    made: 'Art and music made in ContentPad Studio · code by Claude',
    scoreLabel: 'Best total',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/6402676d-dc77-4014-9ccd-39cd14f81267.png',
    accent: '#ff4fb3',
    released: '2026-10-04',
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'tre-and-jada',
    file: 'tre-and-jada.html',
    title: 'Tre & Jada',
    badge: 'Episode 1 · Payday',
    rating: '18+',
    tagline: 'Keep the relationship alive. Keep your wallet alive. Pick one.',
    about: 'A fully voiced, choose-your-path relationship comedy for grown folks, set in Brooklyn. One week, payday to rent day: a brunch ambush and a "man pays for everything" table debate, a double shift on Flatbush, the group chat, a DUMBO photo shoot for the gram, the mall, a Williamsburg restaurant with no prices, and her mama\'s potato salad. Seven mini-games, animated cutscenes, nine endings. Most of them are your fault.',
    genre: 'Story comedy',
    tags: ['18+', 'Comedy', 'Brooklyn', '7 mini-games', '9 endings', 'Voiced'],
    controls: [['Click / tap / Space / (A)', 'Next line'], ['1 · 2 · 3 / ↑ ↓ / d-pad', 'Pick a choice'], ['Esc / Start', 'Pause and settings'], ['Y', 'Auto-play'], ['L / X', 'Dialogue log']],
    by: 'ContentPad Studios',
    made: 'Art, voices and music made in ContentPad Studio (ElevenLabs) · written and coded by Claude',
    scoreLabel: 'Endings found',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/f65c9ecd-ff8b-43cf-ab89-76f862120282.png',
    accent: '#ff4fd8',
    released: '2026-10-03',
    controller: true, mobile: true,
    status: 'live'
  }
];
