/* ContentPad Arcade — the game catalog (build 2026100901-pp).
   House games live in this repo as <slug>.html at the top level and are listed here.
   Only status:'live' entries are shown. noBoard: party games with no global leaderboard (play.html hides the card). rating marks adult games (the game itself runs its own age gate).
   landing: the brand landing page that wraps the game, if it has one (listed under "Brand pages").
   2026-10-07: Arcade HQ → Games can switch any game to live / hidden / off without touching this
   file (gate.js asks the API). status here only says whether the game exists in the Arcade at all. */
window.ARCADE_GAMES = [
  {
    slug: 'pregame-leaked',
    file: 'pregame-leaked.html',
    landing: { url: 'pregame-papers.html', title: 'Pregame Papers', brand: 'Pregame Papers' },
    title: 'Pregame Papers: Leaked',
    badge: 'New · The group chat game · party on the TV',
    tagline: 'Somebody leaked the group chats. Fill the blanks blind, then perform them out loud.',
    about: "The Arcade twin of the printable Leaked book from Pregame Papers. Sixteen fake group chats, from Mom learning emojis and the 2:14 AM ex to the HOA, the fantasy league punishment vote and the wedding speech draft. Put it on the TV and add your friends: the game casts real people in the room as each role, then asks everyone in turn for words (a body part, a celebrity, a player's name) without showing the chat. Then the chat plays out bubble by bubble with typing dots, and each cast member reads their own lines. Turn on read-aloud if nobody is brave. Vote the funniest word Screenshot of the Night; whoever gave it gets a star, and the first to five wins. Solo mode chaos-fills the blanks from an unhinged word bank or lets you fill them yourself. Every chat saves as a screenshot for the real group chat. Crude adult humor. 21+.",
    genre: 'Party',
    tags: ['21+', 'Party game', 'Pass and play', 'Group chat', 'Fill in the blanks', 'Pregame Papers', 'Printable', 'Controller'],
    controls: [['Type / tap', 'Names and words'], ['Space / Enter / (A) / tap the phone', 'Next message'], ['🎲 / X / (X)', 'Random word'], ['← → ↑ ↓ / d-pad', 'Move between buttons'], ['Esc / (B)', 'Back'], ['M', 'Sound']],
    by: 'ContentPad Studios · Pregame Papers',
    made: 'The cover and the cast avatars made in ContentPad Studio · the chats are from the Pregame Papers printable · code by Claude',
    scoreLabel: 'Leaks performed',
    quietSync: true,
    noBoard: true,
    cover: 'https://arcade.contentpad.io/pp/cover-leaked.jpg',
    accent: '#C6FF3D',
    released: '2026-10-09',
    rating: '21+',
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'pregame-yearbook',
    file: 'pregame-yearbook.html',
    landing: { url: 'pregame-papers.html', title: 'Pregame Papers', brand: 'Pregame Papers' },
    title: 'Pregame Papers: The Unhinged Yearbook',
    badge: 'New · Class of Bad Decisions · party on the TV',
    tagline: 'Vote your friends into crude superlatives, draw their yearbook photo, crown the Valedictorian of Bad Decisions.',
    about: "The Arcade twin of the printable Unhinged Yearbook from Pregame Papers. Put it on the big screen and add the class. A superlative comes up (Most Likely to Sext Their Boss by Accident, Best Situationship, Most Likely to Get Banned From a 24-Hour Diner), the countdown hits 3, 2, 1, VOTE, and everyone points. Tap the winner; a tie means fifteen seconds each to argue why you don't deserve it. The player on the winner's left gets sixty seconds to draw their yearbook photo on screen with a finger, a mouse or a controller, and the winner gives a quote for the page. 44 superlatives plus write your own. Graduation crowns the Valedictorian of Bad Decisions, and the whole yearbook saves as one picture. Crude adult humor. 21+.",
    genre: 'Party',
    tags: ['21+', 'Party game', 'Pass and play', 'Drawing', 'Superlatives', 'Pregame Papers', 'Printable', 'Controller'],
    controls: [['Type / tap', 'Names, write-ins and quotes'], ['Tap / mouse / left stick + (A)', 'Draw'], ['X / (X)', 'Next color'], ['Y / (Y)', 'Undo'], ['← → ↑ ↓ / d-pad', 'Move between buttons'], ['Esc / (B)', 'Back'], ['M', 'Sound']],
    by: 'ContentPad Studios · Pregame Papers',
    made: 'The class mascot and cover made in ContentPad Studio · superlatives from the Pregame Papers printable · code by Claude',
    scoreLabel: 'Yearbooks made',
    quietSync: true,
    noBoard: true,
    cover: 'https://arcade.contentpad.io/pp/cover-yearbook.jpg',
    accent: '#E8C463',
    released: '2026-10-09',
    rating: '21+',
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'oak-hill-farm',
    file: 'oak-hill-farm.html',
    title: 'Oak Hill Farm: Farm Friends',
    badge: 'Updated · 4 seasons, story levels, coloring · 2 players',
    tagline: 'Four seasons of chores at Oak Hill Farm, plus story levels, bonus games and a coloring book. Make friends with every animal!',
    about: "Be a farmhand at Oak Hill Farm in Holmdel, New Jersey, and meet the real animals who live there: Boots the Clydesdale and Nugget, the mini ponies Brunello, Molly and Rosie, Cookie and Paris the mules, Charlotte and Penelope the donkeys, the Highland cows Prosciutto, Pearl, George and Hazel, Lola the Jersey cow, Mo, Larry and Curley the curly black-faced sheep, the blue-eyed goats Armani, Speckles and Kiwi, the alpacas Gaby, Bianca, Amina and Tracey, Peter the Peacock, Rodney the show rooster and the special chickens of the Chicken Dome. Travel the Farm Map through fall, winter, spring and summer: 32 story days of chores, from blankets and frozen troughs to planting the garden, building a snowman and cooling everyone off with the hose. In between are bonus games (Egg Catch, King of the Spools, Peter's Feather Match and Alpaca Spa) and story levels from the Oak Hill Farm mini books: The Great Pumpkin Roll, Rodney Oversleeps and Peekaboo, George! Every animal has friendship hearts: learn their favorite treat, dress them up with bows and hats, hear their secrets and become best friends. Color every page of the Oak Hill Farm coloring books right in the game, then save or print them. Play with a friend on one keyboard or two controllers, turn on read-aloud so little ones can play on their own, and look for the secret codes hidden in the coloring books and at the farm. No way to lose. Made for kids.",
    genre: 'Kids',
    tags: ['Kids', 'Farm', 'Animals', 'Oak Hill Farm', 'Seasons', 'Coloring', '2 players', 'Read aloud', 'Truck', 'Controller'],
    controls: [['← → ↑ ↓ / WASD / left stick / drag', 'Walk (or drive)'], ['Space / Enter / (A) / yellow button', 'Pick up, feed, pet, pour · hold to brush, spray, rake or break ice'], ['T / F / (X) / truck button', 'Hop in or out of the farm truck'], ['2 players', 'P1: WASD + Space, F truck · P2: arrows + Enter, / truck · or two controllers'], ['🏠 / H', 'Back to the Farm Map'], ['L / (Y) / 📖', 'Farm Friends album'], ['Esc / P / Start', 'Pause'], ['M', 'Sound']],
    by: 'ContentPad Studios × Oak Hill Farm',
    made: 'The animals, seasons and Farm Maps are drawn from the Oak Hill Farm coloring book and brought to life in color in ContentPad Studio, with the barn, the Chicken Dome and the blue farm truck · theme "Chore Day at Oak Hill" made in ContentPad · code by Claude',
    scoreLabel: 'Stars earned',
    cover: 'https://arcade.contentpad.io/ohf/cover.jpg',
    accent: '#8fd16a',
    released: '2026-10-10',
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'night-drive',
    file: 'night-drive.html',
    title: 'YESTERDAYLAND: Night Drive',
    badge: 'New · Las Vegas, Hot Pursuit, traffic · 2 players',
    tagline: 'Go back for a while. Six night drives, 1984 to 1986. Race them, or outrun the police.',
    about: "A behind-the-car 3D racer set in YESTERDAYLAND, the show about places you remember and times you never actually lived, opening with a dreamlike intro film. Race six night drives: Sunset Boulevard in Los Angeles at dusk, 1985; the Southern California freeway at midnight, 1984; the desert Southwest, 1985; rainy Manhattan, 1984; Ocean Drive, Miami, 1986; and the Las Vegas Strip, 1986. Period traffic fills the roads, coming at you wherever there's a double yellow line. Grand Prix puts you against five rivals, and a top-3 finish opens the next drive. Free Race lets you pick any drive, the laps, the rivals, the difficulty and the traffic. Hot Pursuit sends black-and-white police cruisers after you: don't let them box you in, ram them for takedowns, and find the gap in the roadblock on the last lap. Time Trial races your own ghost for the lap-record boards. 2 Players splits the screen. Win cash, then buy and upgrade five original period cars in the Garage: engine, tires, nitro and paint.",
    genre: 'Racing',
    tags: ['Racing', '3D', 'YESTERDAYLAND', 'Police chase', 'Traffic', '2 players', 'Split screen', 'Time trial', 'Garage', 'Controller'],
    controls: [['↑ / W / RT / (A)', 'Gas'], ['↓ / S / LT / (B)', 'Brake and reverse'], ['← → / A D / left stick', 'Steer'], ['Space / (X) (Y)', 'Nitro'], ['Shift / RB LB', 'Drift: hold through a corner, let go for a turbo'], ['C / Select', 'Camera'], ['Esc / P / Start', 'Pause'], ['M', 'Sound'], ['Touch', 'Gas is automatic: slide to steer, Brake / Nitro / Drift on the right']],
    by: 'ContentPad Studios · YESTERDAYLAND',
    made: 'Made in ContentPad Studio with the YESTERDAYLAND show bible: the intro film (Seedance 2.5), photo-skinned cars, police cruiser and traffic, building facades, track stills and horizons · music, sound and code by Claude',
    scoreLabel: 'Race wins',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/a31bcb5b-75b6-4c8b-811c-b601f36c44aa.jpg',
    accent: '#ffae5c',
    released: '2026-10-08',
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'toy-tokyo-catcher',
    file: 'toy-tokyo-catcher.html',
    landing: { url: 'toytokyo.html', title: 'Toy Tokyo · Gacha World', brand: 'Toy Tokyo' },
    title: 'Gacha Rush: Toy Tokyo UFO Catcher',
    badge: 'New · Toy Tokyo × ContentPad · real pulls',
    tagline: 'Grab a capsule. Every one is a real Toy Tokyo pull, or crew.',
    about: "A claw machine stuffed with capsules from Toy Tokyo, the East Village collectibles shop at 91 Second Avenue. Aim the claw, drop it, and carry your capsule to the prize chute. Crack it open to find a real piece from the shop, from a $6 blind box up to a KAWS-tier grail, with a link to the real thing. You might also get one of the seven original crew stickers: MOKO, Oni-Bot, Kumo, Neko-naut, Daru-G, Hoshi and Kinoko. Grails slip, combos stack, and a full crew binder earns 5 bonus plays. Your binder is saved on this device.",
    genre: 'Arcade',
    tags: ['Claw machine', 'Collectibles', 'Toy Tokyo', 'Binder', 'Controller'],
    controls: [['← → / A D / left stick / drag', 'Aim the claw'], ['Space / Enter / ↓ / (A) / DROP', 'Drop the claw'], ['B / (Y)', 'Open your binder'], ['M', 'Mute'], ['Esc', 'Close a card']],
    by: 'ContentPad Studios × Toy Tokyo',
    made: 'Characters, art and the theme "Second Avenue Gacha" made in ContentPad Studio · products and photos courtesy of Toy Tokyo · code by Claude',
    scoreLabel: 'Best score',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/5f632fc8-2fbd-4cd4-bae8-9e8f842d56c3.png',
    accent: '#ff3ea5',
    released: '2026-10-07',
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'high-flying',
    file: 'high-flying.html',
    title: 'Slappy Tha Bear: High Flying',
    badge: 'New · Slapwoods × ContentPad · twin-stick aim',
    tagline: 'Slappy Tha Bear vs. the Buzzkill Armada. Pew pew pew. Blast your way to the top of the sky.',
    about: "Slappy the Bear, the Slapwoods mascot, straps into his orange starfighter to take the sky back from Baron Buzzkill and the Buzzkill Armada. A 3D rail shooter in the old-school space-fighter style: three stages, from a golden-hour sunset over H-Town, through the lightning of Thunder Canyon, up to the Stratosphere, with a boss gunship at the end of each and the Killjoy Dreadnought waiting at the top. Twin lasers, hold-to-charge lock-on shots, barrel rolls that knock enemy fire away, Slap Bombs, boost and brake. Upgrade from Natural lasers to Russian Cream twins to Bloodshot hyper lasers, grab honey pots and gold rings to fix your shield, wipe out whole formations for bonuses and earn a medal on every stage. Presented by Slapwoods. 21+ only.",
    genre: 'Shooter',
    tags: ['21+', 'Shooter', '3D', '3 stages', 'Bosses', 'Slapwoods', 'Controller'],
    controls: [['WASD / arrows / left stick', 'Fly'], ['Right stick / arrows / mouse', 'Aim — twin-stick, mouse or classic, in Controls & flight'], ['Space / J / RT / click', 'Fire · hold and let go for a lock-on shot'], ['Q / E / LB / RB', 'Barrel roll · or double-tap a direction'], ['B / K / (B)', 'Slap Bomb'], ['Shift / hold (A)', 'Boost — faster while held'], ['C / (Y) / LT', 'Brake'], ['P / Esc / Start', 'Pause'], ['M', 'Mute']],
    by: 'ContentPad Studios × Slapwoods',
    made: 'Art made in ContentPad Studio · Slappy and the Slapwoods logo courtesy of Slapwoods · music, sound and code by Claude',
    scoreLabel: 'Best score',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/c76accf6-c3bb-4794-8f57-6d9f0879f7c5.png',
    accent: '#ff8a1c',
    released: '2026-10-06',
    rating: '21+',
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'dad-casino',
    file: 'dad-casino.html',
    title: "Dex Ain't Dead Casino",
    badge: 'New · Dex is dealing',
    tagline: 'Blackjack, baccarat, roulette, craps and the slots. Dex deals. Play money only.',
    about: "Pull up a seat at Dex Ain't Dead's own casino. Dex deals every table himself, in his own voice: blackjack that pays 3 to 2, baccarat, single-zero roulette, craps with odds, and Dead Man's Jackpot, a five-reel slot with free spins and a 1,000× skull jackpot. DAD Radio plays Dex's records the whole time. Everything is in US dollars to the cent. You start with $10,000 in play money, the house spots you $2,500 when you go broke, and there's a free $2,500 stack every four hours. The lobby tracks your peak bankroll and your lifetime net win or loss. Sign in to the Arcade and your bankroll follows you to any device. Play money only: nothing to buy, nothing to cash out. 18+.",
    genre: 'Casino',
    tags: ['Casino', 'Blackjack', 'Roulette', 'Craps', 'Baccarat', 'Slots', 'Play money', 'Controller'],
    controls: [['Tap a spot', 'Place the selected chip'], ['1 – 6', 'Pick a chip'], ['Space / Enter / Start', 'Deal · spin · roll'], ['H S D P', 'Blackjack: hit, stand, double, split'], ['D-pad + A', 'Move between buttons and press'], ['Esc / B', 'Back to the lobby'], ['M', 'Mute']],
    by: "ContentPad Studios × Dex Ain't Dead",
    made: "Art and Dex's dealer voice made in ContentPad Studio · music by Dex Ain't Dead · code by Claude",
    scoreLabel: 'Peak bankroll',
    scorePrefix: '$',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/227b6d27-8cf7-4ad2-b411-6cf6e9b7e5ee.png',
    accent: '#C9A84C',
    released: '2026-10-04',
    rating: '18+',
    quietSync: true,
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'nightmare-on-46th',
    file: 'nightmare-on-46th.html',
    landing: { url: 'nightmare.html', title: 'Harbor NYC · Halloween', brand: 'Dream Hospitality' },
    title: 'Nightmare on 46th Street',
    badge: 'v5 · throws, launchers, juggles, EX moves, a move list',
    tagline: 'Six legends. One cursed DJ. Survive till 3 AM.',
    about: 'Halloween at Harbor, 621 West 46th Street. At midnight a DJ nobody booked drops a cursed record, the dance floor splits open and New York\'s legends crawl out of the speakers. Pick Vexa the Bottle Queen, Stitch the Doorman, the Rat King, Jack Spokes, Madame 46 or Glow, and fight across the Harbor dance floor, 46th Street, the subway and the rooftop to take down The Headliner. Specials, throws, overheads, launchers and juggles, run attacks, EX specials, counter hits, wall bounces and a Midnight Meter super for every fighter — with a full move list one button away. Every fighter is fully voiced, with their own grunts, move calls, trash talk and signature sounds. Beat the arcade to unlock two secret fighters, or fight a friend in 2-player Versus. Plays with any controller, including 8BitDo.',
    genre: 'Fighting',
    tags: ['Fighting', 'Halloween', 'New York', '8 fighters', 'Voiced', '2 players', 'Controller'],
    controls: [['← → / A D', 'Walk · hold away to block · double-tap forward to run, back to backdash'], ['↑ / W', 'Jump'], ['↓ / S', 'Crouch · crouch + kick sweeps'], ['J / Z', 'Punch · → + punch = overhead'], ['K / X', 'Kick'], ['Punch + Kick', 'Throw (controller X + A) · ← for a back throw · ↓ for a launcher'], ['L / C or ↓↘→ + punch', 'Special · hold punch for an EX special (30 meter)'], ['I / V', 'Super, when the Midnight Meter is full'], ['Tab / controller Y', 'Move list'], ['P / Esc / Start', 'Pause'], ['Versus', 'P1 WASD + F G H T · P2 arrows + , . / ;']],
    by: 'ContentPad Studios × Dream Hospitality',
    made: 'Art, music and announcer made in ContentPad Studio · written and coded by Claude',
    scoreLabel: 'Best score',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/ccc90bc0-3155-47c2-8c1a-a6a9596b4ce6.png',
    accent: '#ff7a1a',
    released: '2026-10-04',
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'skyline-dash',
    file: 'skyline-dash.html',
    title: 'Maverick: Skyline Dash',
    badge: 'v5 · Subway, Airport, Loop City · real kickflips',
    tagline: 'Skate the rooftops. Chain the tricks. Bank the combo.',
    about: 'Maverick took his board to the roofs, then underground, then to the airport. The kickflip is real now: the board leaves his feet and turns over. Heelflips, hardflips, varials, 360 flips, and doubles and triples if you have the air. Hold a grab — frontside, melon or method — and tweak it for more. Shove-it, 360 spin, even a 720 on vert. Grind and boardslide the rails, manual between tricks, launch off ramps and vert quarter-pipes, and roll all the way round loop-de-loops. Dodge rising security gates, ride moving walkways and sliding platforms while express trains blast through the station and planes take off behind you. Bank big combos, grab S-K-A-T-E and earn your crew. Eleven levels — the rooftops, SUBWAY RUSH, TERMINAL 4 and LOOP CITY — then see how far you get in Endless. Every trick works on a controller.',
    genre: 'Skate',
    tags: ['Skateboarding', '11 levels', 'Endless', 'Grabs', 'Loops', 'Crew', 'Controller'],
    controls: [['Space / tap / (A)', 'Ollie — hold for height'], ['Again in the air', 'Kickflip · hold ← heelflip · → hardflip · up to 3'], ['J / K / (Y) / RB / GRAB — hold', 'Grab · ← melon · → method · hold to tweak'], ['↓ / swipe down / TRICK / (X)', 'Shove-it in the air · again = 360 spin'], ['↓ on the ground', 'Manual — keeps your combo alive'], ['↓ on a rail', 'Boardslide'], ['Land on a rail', 'Grind it'], ['Land clean', 'Bank your combo'], ['P / Esc / Start', 'Pause menu'], ['M', 'Mute']],
    by: 'ContentPad Studios',
    made: 'Art and music made in ContentPad Studio · code by Claude',
    scoreLabel: 'Best total',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/6402676d-dc77-4014-9ccd-39cd14f81267.png',
    accent: '#ff4fb3',
    released: '2026-10-05',
    controller: true, mobile: true,
    status: 'live'
  },
  {
    slug: 'tre-and-jada',
    file: 'tre-and-jada.html',
    title: 'Tre & Jada',
    badge: 'Episode 1 · Payday',
    rating: '18+',
    tagline: 'Keep the relationship alive. Keep your wallet alive. Pick one.',
    about: 'A fully voiced, choose-your-path relationship comedy for grown folks, set in Brooklyn. One week, payday to rent day: a brunch ambush and a "man pays for everything" table debate, a double shift on Flatbush, the group chat, a DUMBO photo shoot for the gram, the mall, a Williamsburg restaurant with no prices, and her mama\'s potato salad. Seven mini-games, animated cutscenes, nine endings. Most of them are your fault.',
    genre: 'Story comedy',
    tags: ['18+', 'Comedy', 'Brooklyn', '7 mini-games', '9 endings', 'Voiced'],
    controls: [['Click / tap / Space / (A)', 'Next line'], ['1 · 2 · 3 / ↑ ↓ / d-pad', 'Pick a choice'], ['Esc / Start', 'Pause and settings'], ['Y', 'Auto-play'], ['L / X', 'Dialogue log']],
    by: 'ContentPad Studios',
    made: 'Art, voices and music made in ContentPad Studio (ElevenLabs) · written and coded by Claude',
    scoreLabel: 'Endings found',
    cover: 'https://media.cpdblackbook.com/a2a988e8-fbbd-4510-8238-b1c311f61608/f65c9ecd-ff8b-43cf-ab89-76f862120282.png',
    accent: '#ff4fd8',
    released: '2026-10-03',
    controller: true, mobile: true,
    status: 'live'
  }
];
